/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/f18noanime.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/f18noanime.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="finalsmall" position={[0.098, 1.24, 0.08]} rotation={[0, -0.742, 0]}>
          <group name="five" rotation={[-Math.PI, 1.562, -Math.PI]}>
            <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Material.008']} position={[-0.922, 0.43, -0.044]} rotation={[0, -0.838, 0]} scale={0.045} />
            <mesh name="Sphere016" geometry={nodes.Sphere016.geometry} material={materials['Material.008']} position={[2.254, 0.282, 0.194]} rotation={[0, -0.838, 0]} scale={0.045} />
          </group>
          <group name="four" rotation={[0, Math.PI / 2, 0]}>
            <mesh name="Sphere010" geometry={nodes.Sphere010.geometry} material={materials['Material.008']} position={[-0.505, 0.602, -0.024]} rotation={[0, -0.829, 0]} scale={0.045} />
            <mesh name="Sphere017" geometry={nodes.Sphere017.geometry} material={materials['Material.008']} position={[1.822, 0.021, 0.147]} rotation={[0, -0.829, 0]} scale={0.045} />
          </group>
          <group name="onecir" rotation={[Math.PI, 1.562, 3.141]}>
            <mesh name="Sphere015" geometry={nodes.Sphere015.geometry} material={materials['Material.008']} position={[0.974, 1.076, 0.043]} rotation={[0, -0.838, 0]} scale={0.045} />
            <mesh name="Sphere019" geometry={nodes.Sphere019.geometry} material={materials['Material.008']} position={[0.356, -0.67, 0.074]} rotation={[0, -0.838, 0]} scale={0.045} />
          </group>
          <group name="seccir" rotation={[-Math.PI, 1.562, 3.141]}>
            <mesh name="Sphere014" geometry={nodes.Sphere014.geometry} material={materials['Material.008']} position={[0.433, 0.934, 0.019]} rotation={[0, -0.838, 0]} scale={0.045} />
            <mesh name="Sphere020" geometry={nodes.Sphere020.geometry} material={materials['Material.008']} position={[0.874, -0.45, 0.104]} rotation={[0, -0.838, 0]} scale={0.045} />
          </group>
          <group name="three" rotation={[0, Math.PI / 2, 0]}>
            <mesh name="Sphere013" geometry={nodes.Sphere013.geometry} material={materials['Material.008']} position={[-0.036, 0.773, -0.004]} rotation={[0, -0.829, 0]} scale={0.045} />
            <mesh name="Sphere018" geometry={nodes.Sphere018.geometry} material={materials['Material.008']} position={[1.371, -0.217, 0.121]} rotation={[0, -0.829, 0]} scale={0.045} />
          </group>
          <mesh name="Sphere011" geometry={nodes.Sphere011.geometry} material={materials['Material.001']} rotation={[0, 0.742, 0]} scale={0.243} />
        </group>
        <group name="circleanimef" position={[0.098, 1.24, 0.08]}>
          <mesh name="BezierCircle" geometry={nodes.BezierCircle.geometry} material={materials['Material.008']} position={[0.1, -0.007, 0.089]} rotation={[0, -0.62, -Math.PI / 2]} scale={0.255} />
        </group>
        <group name="Empty001" position={[-1.854, 1.907, 0.506]} rotation={[Math.PI / 2, 0, -0.839]} />
        <group name="Empty002" position={[-4.505, 3.3, 1.954]} rotation={[Math.PI / 2, 0, -0.77]} />
        <group name="check_line" position={[0.098, 1.24, 0.08]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} />
        <group name="Empty" position={[-5.127, 2.987, 4.858]} rotation={[1.53, 0.044, -0.828]} />
        <mesh name="NurbsPath003" geometry={nodes.NurbsPath003.geometry} material={materials['Material.008']} position={[0.082, 1.222, 0.093]} rotation={[-0.196, 0.567, -2.689]} scale={0.12} />
      </group>
    </group>
  )
}

useGLTF.preload('/f18noanime.glb')
