/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/f20noanime.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/f20noanime.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="circleanimef" position={[0.098, 1.24, 0.08]}>
          <mesh name="center_circle" geometry={nodes.center_circle.geometry} material={materials['Material.008']} position={[0.1, -0.007, 0.089]} rotation={[0, -0.62, -Math.PI / 2]} scale={0.255} />
        </group>
        <group name="finalcir" position={[0.098, 1.24, 0.08]} rotation={[0, 0.838, -0.001]}>
          <group name="five" rotation={[0, 0, 0.001]}>
            <mesh name="dot1" geometry={nodes.dot1.geometry} material={materials['Material.008']} position={[-0.922, 0.43, -0.044]} rotation={[0, -0.838, 0]} scale={0.035} />
            <mesh name="dot6" geometry={nodes.dot6.geometry} material={materials['Material.008']} position={[2.256, 0.275, 0.141]} rotation={[0, -0.838, 0]} scale={0.035} />
          </group>
          <group name="four" rotation={[0, -0.009, 0.001]}>
            <mesh name="dot2" geometry={nodes.dot2.geometry} material={materials['Material.008']} position={[-0.505, 0.602, -0.024]} rotation={[0, -0.829, 0]} scale={0.035} />
            <mesh name="dot7" geometry={nodes.dot7.geometry} material={materials['Material.008']} position={[1.831, 0.014, 0.094]} rotation={[0, -0.829, 0]} scale={0.035} />
          </group>
          <group name="onecir">
            <mesh name="dot5" geometry={nodes.dot5.geometry} material={materials['Material.008']} position={[0.974, 1.076, 0.043]} rotation={[0, -0.838, 0]} scale={0.035} />
            <mesh name="dot9" geometry={nodes.dot9.geometry} material={materials['Material.008']} position={[0.358, -0.684, 0.021]} rotation={[0, -0.838, 0]} scale={0.035} />
          </group>
          <group name="seccir" rotation={[0, 0, 0.001]}>
            <mesh name="dot10" geometry={nodes.dot10.geometry} material={materials['Material.008']} position={[0.876, -0.464, 0.05]} rotation={[0, -0.838, 0]} scale={0.035} />
            <mesh name="dot4" geometry={nodes.dot4.geometry} material={materials['Material.008']} position={[0.433, 0.934, 0.019]} rotation={[0, -0.838, 0]} scale={0.035} />
          </group>
          <group name="three" rotation={[0, -0.009, 0.001]}>
            <mesh name="dot3" geometry={nodes.dot3.geometry} material={materials['Material.008']} position={[-0.036, 0.773, -0.004]} rotation={[0, -0.829, 0]} scale={0.035} />
            <mesh name="dot8" geometry={nodes.dot8.geometry} material={materials['Material.008']} position={[1.373, -0.231, 0.068]} rotation={[0, -0.829, 0]} scale={0.035} />
          </group>
        </group>
        <mesh name="center_ball" geometry={nodes.center_ball.geometry} material={materials['Material.001']} position={[0.098, 1.24, 0.08]} scale={0.243} />
        <mesh name="spiral" geometry={nodes.spiral.geometry} material={materials['Material.008']} position={[0.082, 1.222, 0.093]} rotation={[-0.196, 0.567, -2.689]} scale={0.12} />
      </group>
    </group>
  )
}

useGLTF.preload('/f20noanime.glb')
